"""initial

Revision ID: fb44549e9882
Revises: 
Create Date: 2026-03-29 15:56:22.264013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb44549e9882'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('student', 'school_admin', 'company_admin', 'system_admin', name='roletype'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_accounts_role'), 'accounts', ['role'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('ai_analysis_records',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_ai_analysis_records_account_id'), 'ai_analysis_records', ['account_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('collection', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_knowledge_documents_collection'), 'knowledge_documents', ['collection'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_indexed'), 'knowledge_documents', ['indexed'], unique=False)
    op.create_table('operation_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_operation_logs_account_id'), 'operation_logs', ['account_id'], unique=False)
    op.create_table('scarce_talents',
    sa.Column('talent_id', sa.String(length=36), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('shortage_level', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('talent_id')
    )
    op.create_index(op.f('ix_scarce_talents_province'), 'scarce_talents', ['province'], unique=False)
    op.create_index(op.f('ix_scarce_talents_shortage_level'), 'scarce_talents', ['shortage_level'], unique=False)
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('universities',
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('university_id')
    )
    op.create_table('college_employment',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('college_name', sa.String(length=100), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('graduate_nums', sa.Integer(), nullable=True),
    sa.Column('employed_nums', sa.Integer(), nullable=True),
    sa.Column('employment_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('further_study_nums', sa.Integer(), nullable=True),
    sa.Column('further_study_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('overseas_nums', sa.Integer(), nullable=True),
    sa.Column('overseas_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_salary', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.university_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('employment_warnings',
    sa.Column('warning_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=True),
    sa.Column('warning_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.university_id'], ),
    sa.PrimaryKeyConstraint('warning_id')
    )
    op.create_index(op.f('ix_employment_warnings_handled'), 'employment_warnings', ['handled'], unique=False)
    op.create_index(op.f('ix_employment_warnings_level'), 'employment_warnings', ['level'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_account_id'), 'refresh_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_table('student_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=True),
    sa.Column('student_no', sa.String(length=30), nullable=True),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('province_origin', sa.String(length=20), nullable=True),
    sa.Column('gpa', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('internship', sa.String(length=1000), nullable=True),
    sa.Column('employment_status', sa.Integer(), nullable=True),
    sa.Column('desire_city', sa.String(length=50), nullable=True),
    sa.Column('desire_industry', sa.String(length=100), nullable=True),
    sa.Column('desire_salary_min', sa.Integer(), nullable=True),
    sa.Column('desire_salary_max', sa.Integer(), nullable=True),
    sa.Column('cur_company', sa.String(length=100), nullable=True),
    sa.Column('cur_city', sa.String(length=50), nullable=True),
    sa.Column('cur_industry', sa.String(length=100), nullable=True),
    sa.Column('cur_salary', sa.Integer(), nullable=True),
    sa.Column('resume_url', sa.String(length=255), nullable=True),
    sa.Column('profile_complete', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.university_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_student_profiles_employment_status'), 'student_profiles', ['employment_status'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('min_degree', sa.Integer(), nullable=True),
    sa.Column('min_exp_years', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_job_descriptions_company_id'), 'job_descriptions', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_industry'), 'job_descriptions', ['industry'], unique=False)
    op.create_index(op.f('ix_job_descriptions_status'), 'job_descriptions', ['status'], unique=False)
    op.create_table('job_applications',
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index(op.f('ix_job_applications_account_id'), 'job_applications', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_account_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_job_descriptions_status'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_industry'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_company_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_student_profiles_employment_status'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_account_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_employment_warnings_level'), table_name='employment_warnings')
    op.drop_index(op.f('ix_employment_warnings_handled'), table_name='employment_warnings')
    op.drop_table('employment_warnings')
    op.drop_table('companies')
    op.drop_table('college_employment')
    op.drop_table('universities')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_scarce_talents_shortage_level'), table_name='scarce_talents')
    op.drop_index(op.f('ix_scarce_talents_province'), table_name='scarce_talents')
    op.drop_table('scarce_talents')
    op.drop_index(op.f('ix_operation_logs_account_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_knowledge_documents_indexed'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_collection'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_ai_analysis_records_account_id'), table_name='ai_analysis_records')
    op.drop_table('ai_analysis_records')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_role'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
